name: Deployment
on:
  push:
    branches: [main]
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: update-liara
        run: |
          echo Installing Liara CLI
          sudo npm i -g @liara/cli
      - name: install-project-deps
        run: npm ci
      - name: build
        run: npm run build
      - name: deploy
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
          LIARA_REGION: ${{ secrets.LIARA_REGION }}
          LIARA_APP: ${{ secrets.LIARA_APP }}
        run: |
          cd public
          liara deploy --api-token="$LIARA_TOKEN" --region="$LIARA_REGION" --app="$LIARA_APP" --port=$LIARA_APP_PORT --detach

