name: CD-Example
on:
  push:
    branches: [main]
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
      - name: update-liara
      - name: install-project-deps
        run: npm ci
      - name: build
        run: npm run build
      - name: deploy
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
          LIARA_REGION: ${{ secrets.LIARA_REGION }}
          LIARA_APP: ${{ secrets.LIARA_APP }}
        run: npm run deploy
