name: CD-Example
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: update-liara
        run: |
          echo Installing Liara CLI
          npm i -g @liara/cli@2
      - name: install-gatsby-cli
        run: |
          echo Installing Gatsby CLI
          npm i -g gatsby-cli
      - name: install-project-deps
        run: npm ci
      - name: build
        run: gatsby build
      - name: deploy
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
          LIARA_REGION: ${{ secrets.LIARA_REGION }}
          LIARA_APP: ${{ secrets.LIARA_APP }}
        run: |
          cd public
          liara deploy --api-token="$LIARA_TOKEN" --region="$LIARA_REGION" --app="$LIARA_APP" --detach
