name: Deployment
on:
  push:
    branches: [main]
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Setup Fandogh CLI
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
        run: |
          pip install fandogh-cli
      - name: deploy
        env:
          FANDOGH_SERVICE_NAME: ${{ secrets.FANDOGH_SERVICE_NAME }}
          FANDOGH_USERNAME: ${{ secrets.FANDOGH_USERNAME }}
          FANDOGH_PASSWORD: ${{ secrets.FANDOGH_PASSWORD }}
          APP_DOMAIN: ${{ secrets.APP_DOMAIN }}
        run: |
          fandogh login --username="$FANDOGH_USERNAME" --password="$FANDOGH_PASSWORD"
          fandogh image init --name="$FANDOGH_SERVICE_NAME"
          fandogh image publish --version="$GITHUB_SHA"
          fandogh service deploy --image="$FANDOGH_SERVICE_NAME" --version="$GITHUB_SHA" --name="$FANDOGH_SERVICE_NAME" --port 3000 --hosts="$APP_DOMAIN"

